name: Rust CI

on: [push, pull_request]

jobs:
  build_test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        # Needed for btleplug
        run: |
          sudo apt-get update
          sudo apt-get -y install libdbus-1-dev and pkg-config
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Run checks
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-D warnings"
        with:
          command: test
          args: --all-features

      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --all-targets --all-features -- -D warnings